mvctest/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheSwimTimeSite.ObjectModels;
using TheSwimTimeSite.Models;
using TheSwimTimeSite.Models.ViewModels;

namespace mvctest.Controllers
{
   // [Authorize(Roles = "Admin,Staff")]
    public class CourseController : Controller
    {
        public ICourseService Service;

        public CourseController()
        {
            Service = new CourseService(new ModelStateWrapper(this.ModelState), new CourseRepository());
        }
        public CourseController(ICourseService service)
        {
            Service = service;
        }


        // GET: Course
        public ActionResult Index()
        {
            return View(Service.ListAllCourses());
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View(new CreateEditCourseViewModel(Service.ListAllTerms()));
        }
        [HttpPost]
        public ActionResult Create(CreateEditCourseViewModel input)
        {
            bool test = TryUpdateModel(input);
            Service.CreateCourse(input.Creating);

            if (ModelState.IsValid)
            {
                return RedirectToAction("Index");//redirect to course list
            }
            else
            {
                return View(new CreateEditCourseViewModel(input.Creating, Service.ListAllTerms()));//return view with validation summary
            }
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {

            Course editing = Service.GetCourseByID(id);
            return View(new CreateEditCourseViewModel(editing, Service.ListAllTerms()));
        }
        [HttpPost]
        public ActionResult Edit(CreateEditCourseViewModel input)
        {
            Service.EditCourse(input.Creating);

            if (ModelState.IsValid)
            {
                return RedirectToAction("Index");//redirect to course list
            }
            else
            {
                Course editing = Service.GetCourseByID(input.Creating.CRN);
                return View(new CreateEditCourseViewModel(editing, Service.ListAllTerms()));//return view with validation summary
            }
        }
        [HttpGet]
        public ActionResult Enroll(int id)
        {
            Course editing = Service.GetCourseCompleteByID(id);
            return View(new EnrollmentViewModel(editing, Service.ListAllUsers()));

        }
        [HttpPost]
        public ActionResult Enroll(FormCollection input)//gets the list of Enrolled students from Enrolled
        {
            int courseID = int.Parse(input.GetValues("CourseID").FirstOrDefault().ToString());
            List<int> enrolling = new List<int>();//blank list
            String[] sd = input.GetValues("UnEnrolled");

            if (input.GetValues("Enrolled") != null)
            {
                enrolling = input.GetValues("Enrolled").ToList().Select(int.Parse).ToList();
            }

            Service.AdjustEnrollment(courseID, enrolling);
            //adjust enrollment taken from integer translated list of userID's - to course Editing.CourseID
            return RedirectToAction("Index");
        }
        public ActionResult Demo()
        {
            return View();
        }
    }
}

mvctest/Views/Course/Create.cshtml
@model TheSwimTimeSite.Models.ViewModels.CreateEditCourseViewModel


@{
    ViewBag.Title = "Create";
}
<!DOCTYPE html>
<html>
<head>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />;
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Scripts/JQuery1.6.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.16.custom.min.js")" type="text/javascript"></script>

</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        <div id="multipleUsers">
            <br />
            <fieldset>
                <table>
                    <tr>
                        <td align="left">
                            Title&nbsp&nbsp
                            @Html.EditorFor(model => model.Creating.Title)
                            @Html.ValidationMessageFor(model => model.Creating.Title)
                        </td>
                    </tr>
                    <tr>
                        <td align="left">
                            Course Code
                            @Html.EditorFor(model => model.Creating.courseCode)
                            @Html.ValidationMessageFor(model => model.Creating.courseCode)
                        </td>
                    </tr>
                    <tr>
                        <td align="left">
                            Term
                            @Html.DropDownListFor(m => m.Creating.Term.TermID, Model.TermList, "--")
                            @Html.ValidationMessageFor(model => model.Creating.Term.TermID)
                        </td>
                    </tr>
                    <tr>
                        <td align="left">
                            weekCourseStarts
                            @Html.DropDownListFor(m => m.Creating.DayOfWeek, Model.DaysList, "--")
                        </td>
                    </tr>
                    <tr>
                        <td align="left">
                            courseDuration
                            @Html.DropDownListFor(m => m.Creating.Duration, Model.DurationList, "--")
                        </td>
                    </tr>
                    <tr>
                        <td align="left">
                            courseRunningTime
                            @Html.DropDownListFor(m => m.Creating.TimeOfDay, Model.TimeList, "--")
                        </td>
                    </tr>
                    <tr>
                        <td align="left">
                            Require Checkout
                            @Html.EditorFor(model => model.Creating.CheckOut)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="submit" />
                        </td>
                    </tr>
                </table>
            </fieldset>
            <br />
            <br />
            @Html.ActionLink("Courses", "Index", "Course", null, new { @class = "button" })
        </div>
    }
</body>
</html>

mvctest/Views/Course/Edit.cshtml
@model TheSwimTimeSite.Models.ViewModels.CreateEditCourseViewModel


@{
    ViewBag.Title = "Edit";
}
<!DOCTYPE html>
<html>
<head>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />;
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.HiddenFor(m => m.Creating.CRN)
        <div id="multipleUsers">
            <br />
        
            <fieldset>
                <table>
                    <tr>
                        <td align="left">
                            Title&nbsp&nbsp
                            @Html.EditorFor(model => model.Creating.Title)
                            @Html.ValidationMessageFor(model => model.Creating.Title)
                        </td>
                    </tr>
                    <tr>
                        <td align="left">
                            Course Code
                            @Html.EditorFor(model => model.Creating.courseCode)
                        </td>
                    </tr>
                    <tr>
                        <td align="left">
                            Term
                            @Html.DropDownListFor(m => m.Creating.Term.TermID, Model.TermList, "--")
                        </td>
                    </tr>
                    <tr>
                        <td align="left">
                            weekCourseStarts
                            @Html.DropDownListFor(m => m.Creating.DayOfWeek, Model.DaysList, "--")
                        </td>
                    </tr>
                    <tr>
                        <td align="left">
                            courseDuration
                            @Html.DropDownListFor(m => m.Creating.Duration, Model.DurationList, "--")
                        </td>
                    </tr>
                    <tr>
                        <td align="left">
                            courseRunningTime
                            @Html.DropDownListFor(m => m.Creating.TimeOfDay, Model.TimeList, "--")
                        </td>
                    </tr>
                    <tr>
                        <td align="left">
                            Require Checkout
                            @Html.EditorFor(model => model.Creating.CheckOut)
                        </td>
                    </tr>
                    <tr>
                        <td><input type="submit" value="Save Changes" /></td>
                    </tr>
                </table>
            </fieldset>
           <br />
            <br />
            @Html.ActionLink("Courses", "Index", "Course", null, new { @style = "padding:1px 10px 1px 10px;text-decoration:none;color:white;background-color:red;margin-top:19px;" })
        </div>
    }

</body>
</html>

mvctest/Views/Course/Enroll.cshtml
@model TheSwimTimeSite.Models.ViewModels.EnrollmentViewModel


@{
    ViewBag.Title = "Enroll";
}
<!DOCTYPE html>
<html>
<head>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />;
    <script src="https://code.jquery.com/jquery-1.6.2.js" type="text/javascript"></script>
    <script type="text/javascript">
        var presistUsers;
        $(document).ready(function () {
            //enroll button
            $("#enroller").click(function () {
                var temp = $("#NotEnrolled option[value=" + $("#NotEnrolled").val() + "]"); //get selected object
                $("#NotEnrolled option[value=" + $("#NotEnrolled").val() + "]").remove();
                $("#Enrolled").append($("<option>").attr('value', temp.val()).text(temp.text()));
            });
            $("#deenroller").click(function () {
                var temp = $("#Enrolled option[value=" + $("#Enrolled").val() + "]"); //get selected object
                $("#Enrolled option[value=" + $("#Enrolled").val() + "]").remove();
                $("#NotEnrolled").append($("<option>").attr('value', temp.val()).text(temp.text()));
            });
            //setup post selection to pass results to controller
            $("#poster").click(function () {
                $("#Enrolled option").each(function () {
                    $(this).attr("selected", true);
                });
            });
            //setup search box
            $("#searcher").keyup(function () {
                $("#loading").show();
                clearUsers(); //clear users
                GetUsers($("#searcher").val());
            });
            //get initial list of users
            $("#loading").show();
            presistUsers = @Html.Raw(Model.JsonUsers) ; //get list of users
            $("#loading").hide();
            clearUsers();
            GetUsers("");
        });
        function clearUsers() {
            $("#NotEnrolled").children().remove();
        }
        function GetUsers(search) {//get a list of users filtered and searched
            $("#loading").show();
            var filteredList = presistUsers.slice();
            if (search.length != 0) {
                var len = filteredList.length; //track length
                for (var i = filteredList.length - 1; i >= 0; i--) {//loop through complete list once (lineral traversal)
                    if (filteredList[i].LastName.substring(0, search.length).toUpperCase() != search.toUpperCase()) {
                        filteredList.splice(i, 1); //splice the array
                    }
                }
            }
            //alert(filteredList.length);
            for (pos = 0; pos < filteredList.length; pos++) {
                $("#NotEnrolled").append("<option value='" + filteredList[pos].UserID + "'>" + filteredList[pos].FirstName + " " + filteredList[pos].LastName + "</option>");
            }
            $("#loading").hide();
        }


    </script>
  
</head>
<body>
   @using (Html.BeginForm())
   {
    @Html.HiddenFor(model => model.CourseID)
    <div id="certifyBackground">
        <br />
        <fieldset>
            <legend>@Model.Editing.Title @Model.Editing.CRN</legend>
            <center>
                <table>
                    <tr>
                        <td>
                            Search by Last Name: <input id="searcher" type="text" />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <img id="loading" src="@Url.Content("~/Images/loading.gif")" alt="working..." />
                            <select id="NotEnrolled" size="10" style="width:100px;"></select>
                        <td>
                            <input id="enroller" type="button" value=" Enroll >> " /><br />
                            <input id="deenroller" type="button" value="<< UnEnroll" />
                        </td>
                        <td>@Html.ListBox("Enrolled", Model.Enrolled)</td>
                        
                                
                    </tr>
                    <tr>
                        <td><input id="poster" type="submit" value="Save" style="float:right;" /></td>
                    </tr>
                </table>
            </center>
        </fieldset>
        @Html.ActionLink("Courses", "Index", new { @class = "button" })

    </div>
   }
</body>
</html>

mvctest/Views/Course/Index.cshtml
@model IEnumerable <TheSwimTimeSite.ObjectModels.Course>


@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>
<html>
<head>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />;
</head>
<body>
    <div id="multipleUsers">
        <br />
        <br />
        @Html.ActionLink("Create", "Create", "Course", null, new { @style = "padding:10px 10px 10px 10px;text-decoration:none;color:white;background-color:red;" })
        <br />
        <br />
        <br />
        <table>
                <tr>
                    <th style="border:1px solid #dddddd;padding:8px; text-align:left;">
                        &nbsp&nbsp&nbspTitle
                    </th>
                    <th  style="border:1px solid #dddddd;padding:8px; text-align:left;">
                        Course Code
                    </th>
                    <th style="border:1px solid #dddddd;padding:8px; text-align:left;">
                        startDayOfCourse
                    </th>
                    <th style="border:1px solid #dddddd;padding:8px; text-align:left;">
                        DurationOfCourse
                    </th>
                    <th style="border:1px solid #dddddd;padding:8px; text-align:left;">
                        HoursCourseRuns
                    </th>
                    <th style="border:1px solid #dddddd;padding:8px; text-align:left;">
                        Checkout
                    </th>
                    <th></th>
                </tr>
            @foreach(var item in Model)
            {
                <tr>
                    <td style="border:1px solid #dddddd;padding:8px; text-align:left;">
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td style="border:1px solid #dddddd;padding:8px; text-align:left;">
                        @Html.DisplayFor(modelItem => item.courseCode)
                    </td>
                    <td style="border:1px solid #dddddd;padding:8px; text-align:left;">
                        @item.DayString()
                    </td>
                    <td style="border:1px solid #dddddd;padding:8px; text-align:left;">
                        <span>@item.DurationString()</span>
                    </td>
                    <td style="border:1px solid #dddddd;padding:8px; text-align:left;">
                        <span>@item.TimeString()</span>
                    </td>
                    <td style="border:1px solid #dddddd;padding:8px; text-align:left;">
                        @Html.DisplayFor(modelItem => item.CheckOut)
                    </td>
                    <td style="border:1px solid #dddddd;padding:8px; text-align:left;">
                        @Html.ActionLink("Edit", "Edit", new { id = item.CRN }) |
                        @Html.ActionLink("Enrollment", "Enroll", new { id = item.CRN })
                    </td>
                </tr>
            }

            </table>
       
            
    </div>
</body>
</html>