mvctest/Controllers/ReportsController.cs
using mvctest.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheSwimTimeSite.Models;
using TheSwimTimeSite.ObjectModels;

namespace mvctest.Controllers
{
    [CustomAuthorize(Roles = "Admin")]
    public class ReportsController : Controller
    {
        private IReportsService Service;

        public ReportsController()
        {
            Service = new ReportsService(new ModelStateWrapper(this.ModelState), new ReportsRepository());
        }
     
        public ReportsController(IReportsService service)
        {
            Service = service;
        }


        [HttpGet]
        public ActionResult ReportIndex()
        {
            return View(new Report(DateTime.Now.AddMonths(-1).Date, DateTime.Now, "", false));
        }
        [HttpPost]
        public ActionResult ReportIndex(Report input)
        {
            Report masterReport = Service.GenerateReport(input);
            if (ModelState.IsValid)
            {
                //HeaderRow = "userID, lastName, firstName, userType, classInSchool, Date, Time, visitType, inOut";
                //Report test = new Report(DateTime.Parse("1/1/1990"), DateTime.Now);
                //Report masterReport = Service.GenerateReport(input);
                String csv = masterReport.HeaderRow + "\n";
                foreach (ReportRow row in masterReport.Data)
                {
                    csv += row.CSVToString();
                }
                System.Text.ASCIIEncoding encoding = new System.Text.ASCIIEncoding();
                Byte[] bytes = encoding.GetBytes(csv);
                return File(bytes, "text/csv", masterReport.FileName + ".csv");

            }
            else
            {
                return View(input);
            }

        }
        [HttpGet]
        public ActionResult IndividualReport()
        {
            //List<User> ret = Service.ListUsers();
            return View(new Report(DateTime.Now.AddMonths(-1).Date, DateTime.Now, "", false));
        }

        [HttpPost]
        public ActionResult IndividualReport(Report input)
        {
            Report indiReport = Service.GenerateIndividualReport(input);
            if (ModelState.IsValid)
            {
                String csv = indiReport.HeaderRow + "\n";
                foreach (ReportRow row in indiReport.Data)
                {
                    csv += row.CSVToString();
                }
                System.Text.ASCIIEncoding encoding = new System.Text.ASCIIEncoding();
                Byte[] bytes = encoding.GetBytes(csv);
                return File(bytes, "text/csv", indiReport.FileName + ".csv");

            }
            else
            {
                return View(input);
            }

        }



        public ActionResult TrendReport()
        {
            return View();
        }
       
        public ActionResult classReport()
        {
            return View();  
        }
    }
}

mvctest/Views/Reports/IndividualReport.cshtml
@model TheSwimTimeSite.ObjectModels.Report


@{
   }

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />;
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Scripts/JQuery1.6.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.16.custom.min.js")" type="text/javascript"></script>

   
</head>
<body>
    @using (Html.BeginForm()){ 
    <div id="certifyBackground">
        <div id="reports-left" style="background-color:#F0F0F0">
            <br />
            <fieldset>
                <legend>Generate Individual Student Report: </legend>
                <!-- Enter new stuff BELOW this comment -->
                <div class="small-container">
                    <div class="editor-label">
                        Report Start Date
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.Start,
           new { @class = "datepicker" })
                        @Html.ValidationMessageFor(model => model.Start)
                    </div>

                    <div class="editor-label">
                        Report End Date
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.Finish,
                          new { @class = "datepicker" })
                        @Html.ValidationMessageFor(model => model.Finish)
                    </div>

                    <div class="editor-label">
                        Student First Name
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.First)
                        @Html.ValidationMessageFor(model => model.First)
                    </div>

                    <div class="editor-label">
                        Student Last Name
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.Last)
                        @Html.ValidationMessageFor(model => model.Last)
                    </div>

                    <div class="editor-label">
                        File Name
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.FileName)
                        @Html.ValidationMessageFor(model => model.FileName)
                    </div>
                    <div>
                        @Html.EditorFor(model => model.IncludeOuts) Include Checkouts/Invalids
                    </div>

                    <div style="padding: 30px;">
                        <input type="submit" value="Generate Report" class="gen-submit" />
                    </div>
                </div>
            </fieldset>
        </div>
        <div id="reports-right" style="background-color:#F0F0F0">
            <fieldset>
                <legend>Reports Home </legend>
                <div class="smaller-container">
                    <table class="no-borders" style="width: 100%;">
                        <tr class="no-borders"><td class="no-side-borders">@Html.ActionLink("General Reports", "ReportIndex", null, new { @class = "button" })</td></tr>



                    </table>
                </div>
            </fieldset>
        </div>
    </div>
    
    
    }
</body>
</html>

mvctest/Views/Reports/ReportIndex.cshtml
@model TheSwimTimeSite.ObjectModels.Report


@{
    ViewBag.Title = "ReportIndex";
}
<!DOCTYPE html>
<html>
<head>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />;
</head>
<body>
   @using (Html.BeginForm())
   {
    <div id="reportbackground">
        <h2 id="reportTitle">Reports</h2>
        <fieldset>
            <legend>Generate General Usage Report</legend>
            <p>Report Start Date</p>
            @Html.TextBoxFor(model => model.Start, new {@class ="reporttextboxes"})
            
            <p>Report End Date</p>
            @Html.TextBoxFor(model => model.Finish, new { @class = "reporttextboxes" })
            <p>File Name</p>
            @Html.TextBoxFor(model => model.FileName)
            <p></p>
            <input type="checkbox" />Include CheckOut/Invalids
            <p></p>
            <input type="submit" value="Generate Report" />
        </fieldset>
        <div id="otherReportTools">
            <fieldset>
                <legend>Other Reporting Tools</legend>
                @Html.ActionLink("IndividualReporting", "IndividualReport", "Reports", null, new { @class = "button" })
                <p></p>
                @Html.ActionLink("Class Reporting", "classReport", "Reports", null, new { @class = "button" })
                <p></p>
                @Html.ActionLink("Trend Reporting", "TrendReport", "Reports", null, new { @class = "button" })
            </fieldset>
        </div>
        <div id="reportHomeButton">
            <button>Home</button>
        </div>

    </div>
   }
</body>
</html>

mvctest/Views/Reports/TrendReport.cshtml
@{
    ViewBag.Title = "TrendReport";
}

<!DOCTYPE html>
<html>
<head>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />;
</head>
<body>
    <div id="certifyBackground">
        <br />
        <p>
            Generate Report
        </p>
        <button>Report</button>
       
    </div>
</body>
</html>

mvctest/Views/Reports/classReport.cshtml
@{
    ViewBag.Title = "classReport";
}

<!DOCTYPE html>
<html>
<head>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />;
</head>
<body>
    <div id="certifyBackground">
        <br />
        <p>CourseName/Course ID</p>
        <input type="text" />
        <p>
            Generate Report
        </p>
        <button>Report</button>

    </div>
</body>
</html>