mvctest/Controllers/SetUpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheSwimTimeSite.Models;
using TheSwimTimeSite.ObjectModels;
using TheSwimTimeSite.Models.ViewModels;
using Newtonsoft.Json;
using mvctest.Security;

namespace mvctest.Controllers
{
    //[CustomAuthorize(Roles = "Admin")]

    public class SetUpController : Controller
    {
        private ISetupService Service;


        public SetUpController()
        {
            Service = new SetupService(new ModelStateWrapper(this.ModelState), new SetupRepository());
        }

        public SetUpController(ISetupService service)
        {
            Service = service;
        }
        
        // GET: SetUp
        public ActionResult SetUpIndex()
        {
            return View();
        }
        public ActionResult Certifications()
        {
            return View();
        }
        public ActionResult SwimTime()
        {
            return View(Service.ListAllSwimTime());
        }
        public ActionResult Comment()
        {
            return View();
        }
        public ActionResult createCertification()
        {
            return View();
        }
        [HttpGet]
        public ActionResult createSwimTime()
        {
            CreateEditSwimTimeRulesViewModel model = new CreateEditSwimTimeRulesViewModel(Service.ListAllCourses());
            return View(model);
        }
        [HttpPost]
        public ActionResult createSwimTime(CreateEditSwimTimeRulesViewModel input)
        {
            TryUpdateModel(input);
            if (!Service.CreateSwimTime(input.Creating))
            {
                CreateEditSwimTimeRulesViewModel model = new CreateEditSwimTimeRulesViewModel(Service.ListAllCourses(), input.Creating);
                return View(model);
            }
            else
            {
                return RedirectToAction("SwimTime");//Default valud here now
            }
        }
        [HttpGet]
        public ActionResult createTerm()
        {
            CreateEditTermViewModel model = new CreateEditTermViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult createTerm(CreateEditTermViewModel input)
        {
            TryUpdateModel(input);
            if (!Service.CreateTerm(input.Creating))
            {
                CreateEditTermViewModel model = new CreateEditTermViewModel();
                return View(model);
            }
            else
            {
                return RedirectToAction("Terms");//Default valud here now
            }
        }
        [HttpGet]
        public ActionResult createVisitType()
        {
            return View(new VisitType());
        }
        [HttpPost]
        public ActionResult CreateVisitType(VisitType creating)
        {
            if (!Service.CreateVisitType(creating))
            {
              
                return View();
            }

            return RedirectToAction("visitType");//redirect to equipment list

        }

        public ActionResult editCertification()
        {
            return View();
        }
        [HttpGet]
        public ActionResult editSwimTime(int id)
        {
            SwimTime editing = Service.GetSwimTimeByID(id);
            return View(new CreateEditSwimTimeRulesViewModel(editing, Service.ListAllCourses()));
        }
        [HttpPost]
        public ActionResult editSwimTime(CreateEditSwimTimeRulesViewModel input)
        {
            TryUpdateModel(input);
            if (!Service.EditSwimTime(input.Creating))
            {
                CreateEditSwimTimeRulesViewModel model = new CreateEditSwimTimeRulesViewModel(Service.ListAllCourses(), input.Creating);
                return View(model);
            }
            else
            {
                return RedirectToAction("SwimTime");//Default valud here now
            }
        }

        [HttpGet]
        public ActionResult editTerm(int id)
        {
            Term editing = Service.GetTermByID(id);

            return View(new CreateEditTermViewModel(editing));
        }
        [HttpPost]
        public ActionResult editTerm(CreateEditTermViewModel input)
        {
            Service.EditTerm(input.Creating);

             if (ModelState.IsValid)
             {
                 return RedirectToAction("Terms");//redirect to term list
             }
             else
             {
                 return View(input);//return view with validation summary
             }

        }
        [HttpGet]
        public ActionResult editVisitType(int id)
        {
            return View(Service.GetVisitTypeByID(id));
        }
        [HttpPost]
        public ActionResult EditVisitType(VisitType editing)
        {
            if (!Service.EditVisitType(editing))
            {
               
                return View();
            }

            return RedirectToAction("VisitType");//redirect to equipment list
        }

        public ActionResult Terms()
        {
        
            return View(Service.ListAllTerms());
        }
        public ActionResult visitType()
        {
            return View(Service.ListAllVisitTypes());
        }
    }
}

mvctest/Views/SetUp/Certifications.cshtml
@{
    ViewBag.Title = "Certifications";
}
<!DOCTYPE html>
<html>
<head>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />;
</head>
<body>
    <div id="background">
        <h2 align="left" style="margin-top:-500px; margin-left:30px;">Certifications</h2>
        <p></p>
        <button style="margin-right:750px;padding:10px 9px 10px 9px;">Create Certification</button>

        <center>
             <br />
             <fieldset>
                <table>
                    <tr>
                        <th style="padding-right:300px;">
                            Title
                        </th>
                        <th style="padding-right:300px;">
                            Description
                        </th>
                        <th>
                            Active
                        </th>
                        <th></th>
                    </tr>
                    <tr>
                        <td>

                        </td>
                        <td>

                        </td>
                        <td>

                        </td>
                        <td>
                            <a href="#" style="margin-left:17px;">Edit</a>
                        </td>
                    </tr>
                </table>
            </fieldset>
            <br />
        </center>
        <button style="margin-left:800px;padding:10px 19px 10px 19px;">SetUp</button>
    </div>
</body>
</html>

mvctest/Views/SetUp/Comment.cshtml
@model IEnumerable<TheSwimTimeSite.ObjectModels.Comment>


@{
    ViewBag.Title = "Comment";
}

<!DOCTYPE html>
<html>
<head>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />;
</head>
<body>
    <div id="background">
        <center>
            <table style="margin-top:-490px;border-collapse:collapse;width:98%;">
                <tr>
                    <th style="border:1px solid #dddddd;padding:8px; text-align:left;">
                        Title
                    </th>
                    <th style="border:1px solid #dddddd;padding:8px; text-align:left;">
                        Text
                    </th>
                    <th style="border:1px solid #dddddd;padding:8px; text-align:left;">
                        DatePosted
                    </th>
                    <th></th>
                </tr>
               @foreach (var item in Model)
               {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Text)
                    </td>
                    <td>
                        <span>@item.DatePosted.ToShortDateString()</span>
                    </td>
                </tr>
               }
            </table>
            <br />
        </center>
        @Html.ActionLink("Setup Home", "SetUpIndex", null, new { @class = "button" })
    </div>
</body>
</html>

mvctest/Views/SetUp/SetUpIndex.cshtml
@{
    ViewBag.Title = "SetUpIndex";
}
<!DOCTYPE html>
<html>
<head>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />;
</head>
<body>
    <div id="setupBackground">
        
    </div>
    <div id="setupWord">
        <p>Setup Home</p>
    </div>
    <div class="setupButtonClass">
         @Html.ActionLink("VisitTypes", "visitType",null, new { @style = "padding:10px 10px 10px 14px;text-decoration:none;color:white;background-color:red;margin-right:30px"  })

         @Html.ActionLink("Terms", "Terms", null,new { @style = "padding:10px 25px 10px 25px;text-decoration:none;color:white;background-color:red;margin-right:30px" })
         @Html.ActionLink("SwimTime", "SwimTime", null, new { @style = "padding:10px 25px 10px 25px;text-decoration:none;color:white;background-color:red;margin-right:30px" })

        <p></p>
        <br />
        @Html.ActionLink("Courses", "Index", "Course",null, new { @style = "padding:10px 25px 10px 25px;text-decoration:none;color:white;background-color:red;margin-right:50px" })
      
    </div>
</body>
</html>

mvctest/Views/SetUp/SwimTime.cshtml
@model IEnumerable <TheSwimTimeSite.ObjectModels.SwimTime>


@{
    ViewBag.Title = "SwimTime";
}

<!DOCTYPE html>
<html>
<head>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />;
</head>
<body>
    <div id="swimTimebackground">
        <br />
        <h2 style="margin-top:-500px;margin-right:750px;">SwimTime</h2>
        <p>
            @Html.ActionLink("Create New", "CreateSwimTime", null, new {@style = "padding:10px 10px 10px 10px;text-decoration:none;color:white;background-color:red;" })
        </p>
        <br />
        <table style="border-collapse:collapse;width:98%;">
            <tr>
                <th style="border:1px solid #dddddd;padding:8px; text-align:left;">
                    <p>Course</p>
                </th>
             
                <th style="border:1px solid #dddddd;padding:8px; text-align:left;">
                    <p>Min Hours / Visit</p>
                </th>
                <th style="border:1px solid #dddddd;padding:8px; text-align:left;">
                    <p>Max Hours / Visit</p>
                </th>
                <th style="border:1px solid #dddddd;padding:8px; text-align:left;">
                    <p>Start Date</p>
                </th>
                <th style="border:1px solid #dddddd;padding:8px; text-align:left;">
                    <p>End Date</p>
                </th>
               
                <th></th>
            </tr>
         @foreach (var item in Model)
         {
            <tr>
                <td style="border:1px solid #dddddd;padding:8px; text-align:left;">
                    @Html.DisplayFor(modelItem => item.Course.courseCode)
                </td>
              
                <td style="border:1px solid #dddddd;padding:8px; text-align:left;">
                    @Html.DisplayFor(modelItem => item.MinHoursPerVisit)
                </td>
                <td  style="border:1px solid #dddddd;padding:8px; text-align:left;">
                    @Html.DisplayFor(modelItem => item.MaxHoursPerVisit)
                </td>
                <td style="border:1px solid #dddddd;padding:8px; text-align:left;"> 
                    @Html.DisplayFor(modelItem => item.Start)
                </td>
                <td style="border:1px solid #dddddd;padding:8px; text-align:left;">
                    @Html.DisplayFor(modelItem => item.End)
                </td>
              
                <td style="border:1px solid #dddddd;padding:8px; text-align:left;">
                    @Html.ActionLink("Edit", "EditSwimTime", new { id = item.SwimTimeID })
                </td>
            </tr>
         }
        </table>
        <br />
        <br />
        @Html.ActionLink("Setup Home", "SetUpIndex", null, new {@style = "padding:10px 10px 10px 10px;text-decoration:none;color:white;background-color:red;" })
    </div>
</body>
</html>

mvctest/Views/SetUp/Terms.cshtml
@model IEnumerable <TheSwimTimeSite.ObjectModels.Term>



@{
    ViewBag.Title = "Terms";

}

<!DOCTYPE html>
<html>
<head>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />;
</head>
<body>
    
    <div id="certifyBackground">
        <br />
        @Html.ActionLink("Create New","CreateTerm","SetUp",null,new { @style = "padding:10px 10px 10px 10px;text-decoration:none;color:white;background-color:red;" })
        <br />
        <br />

        <table style="width:80%;">
            
            <tr>
                <th style="border:1px solid #dddddd;padding:8px; text-align:left;">
                    Quarter
                </th>
                <th style="border:1px solid #dddddd;padding:8px; text-align:left;">
                    Year
                </th>
                <th style="border:1px solid #dddddd;padding:8px; text-align:left;">
                    Start
                </th>
                <th style="border:1px solid #dddddd;padding:8px; text-align:left;">
                    End
                </th>
                <th style="border:1px solid #dddddd;padding:8px; text-align:left;">
                    Title
                </th>
                <th></th>
            </tr>
           @foreach(var item in Model)
           {
               <tr>
                   <td style="border:1px solid #dddddd;padding:8px; text-align:left;">
                       @Html.DisplayFor(modelItem => item.Quarter)
                   </td>
                   <td style="border:1px solid #dddddd;padding:8px; text-align:left;">
                       @Html.DisplayFor(modelItem => item.Year)
                   </td>
                   <td style="border:1px solid #dddddd;padding:8px; text-align:left;">
                       @Html.DisplayFor(modelItem => item.Start)
                   </td>
                   <td style="border:1px solid #dddddd;padding:8px; text-align:left;">
                       @Html.DisplayFor(modelItem => item.Endd)
                   </td>
                   <td style="border:1px solid #dddddd;padding:8px; text-align:left;">
                       @Html.DisplayFor(modelItem => item.Title)
                   </td>
                   <td style="border:1px solid #dddddd;padding:8px; text-align:left;">
                       @Html.ActionLink("Edit", "editTerm", new { id = item.TermID })
                   </td>
               </tr>
           }
        </table>  
        <br />
        <br />
        @Html.ActionLink("SetUpHome", "SetUpIndex",null, new { @style = "padding:10px 10px 10px 10px;text-decoration:none;color:white;background-color:red;" })
        
    </div>
   
</body>
</html>

mvctest/Views/SetUp/createCertification.cshtml
@{
    ViewBag.Title = "createCertification";
}
<!DOCTYPE html>
<html>
<head>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />;
</head>
<body>
    <div id="background">
        <fieldset style="margin-top:-450px;">
            <p style="margin-right:8px;">Title</p>
            <input type="text"/>
            <p>Description</p>
            <input type="text"/>
            <p>Active</p>
            <input type="checkbox"/>
            <p></p>
            <input type="submit" value="Create" />
        </fieldset>
        <br />
        <button style="padding:10px 15px 10px 15px;">Certifications</button>
    </div>
</body>
</html>

mvctest/Views/SetUp/createSwimTime.cshtml
@model TheSwimTimeSite.Models.ViewModels.CreateEditSwimTimeRulesViewModel


@{
    ViewBag.Title = "createSwimTime";
}
<!DOCTYPE html>
<html>
<head>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />;
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Scripts/JQuery1.6.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.16.custom.min.js")" type="text/javascript"></script>


    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {

            $('.datepicker').datepicker();
        });

    </script>
</head>
<body>
   @using (Html.BeginForm())
   {
       @Html.ValidationSummary(true)
    <div id="visitBackground">
        <br />
        <fieldset style="margin-top:-500px;" align="left">
            <legend>SwimTime</legend>
            <table>
                <tr>
                    <td>
                        Min-Hours
                        @Html.EditorFor(model => model.Creating.MinHoursPerVisit)
                        @Html.ValidationMessageFor(model => model.Creating.MinHoursPerVisit)
                    </td>
                </tr>
                <tr>
                    <td>
                        Max-Hours
                        @Html.EditorFor(model => model.Creating.MaxHoursPerVisit)
                        @Html.ValidationMessageFor(model => model.Creating.MaxHoursPerVisit)
                    </td>
                </tr>
                <tr>
                    <td>
                        Start Date
                        @Html.TextBoxFor(model => model.Creating.Start,
                                  new { @class = "datepicker" })
                        @Html.ValidationMessageFor(model => model.Creating.Start)
                    </td>
                </tr>
                <tr>
                    <td>
                        End Date
                        @Html.TextBoxFor(model => model.Creating.End,
                                  new { @class = "datepicker" })
                        @Html.ValidationMessageFor(model => model.Creating.End)
                    </td>
                </tr>
               
                <tr>
                    <td>
                        @Html.LabelFor(model => model.Creating.Course)
                        @Html.DropDownListFor(m => m.Creating.Course.CRN, Model.Course, "--")
                        @Html.ValidationMessageFor(model => model.Creating.Course)

                    </td>
                </tr>
             
                <tr>
                    <td>
                        <br />
                        <input type="submit" value="Save" style="border:none;color:white;background-color:red;padding:4px 20px 4px 20px;" />
                    </td>
                </tr>
            </table>
        </fieldset>

        <br />
        @Html.ActionLink("SwimTime", "SwimTime", null, new { @style = "padding:10px 10px 10px 10px;text-decoration:none;color:white;background-color:red;" })
    </div>
   }
</body>
</html>

mvctest/Views/SetUp/createTerm.cshtml
@model TheSwimTimeSite.Models.ViewModels.CreateEditTermViewModel


@{
    ViewBag.Title = "createTerm";
}

<!DOCTYPE html>
<html>
<head>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />;
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Scripts/JQuery1.6.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.16.custom.min.js")" type="text/javascript"></script>

    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {

            $('.datepicker').datepicker();
        });
    
    </script>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        <div id="visitBackground">
            <fieldset style="margin-top:-420px;">
                <table>
                    <tr>
                        <td align="left">
                            @Html.LabelFor(model => model.Creating.Quarter)
                            @Html.DropDownListFor(m => m.Creating.Quarter, Model.QuartersList, "--")
                            <br />
                            @Html.ValidationMessageFor(model => model.Creating.Quarter)
                        </td>

                    </tr>
                    <tr>
                        <td align="left">
                            @Html.LabelFor(model => model.Creating.Year)
                            @Html.EditorFor(model => model.Creating.Year)
                            @Html.ValidationMessageFor(model => model.Creating.Year)
                        </td>
                    </tr>
                    <tr>
                        <td align="left">
                            @Html.LabelFor(model => model.Creating.Start)
                            @Html.TextBoxFor(model => model.Creating.Start,
                    new { @class = "datepicker" })
                            @Html.ValidationMessageFor(model => model.Creating.Start)
                        </td>
                    </tr>
                    <tr>
                        <td align="left">
                            @Html.LabelFor(model => model.Creating.Endd)
                            @Html.TextBoxFor(model => model.Creating.Endd,
                    new { @class = "datepicker" })
                            @Html.ValidationMessageFor(model => model.Creating.Endd)
                        </td>
                    </tr>
                    <tr>
                        <td><input type="submit" value="Create" /></td>
                    </tr>
                </table>
            </fieldset>
            <br />
            @Html.ActionLink("Terms", "Terms", null, new { @style = "padding:10px 10px 10px 10px;text-decoration:none;color:white;background-color:red;" })
        </div>
    }
</body>
</html>

mvctest/Views/SetUp/createVisitType.cshtml
@model TheSwimTimeSite.ObjectModels.VisitType


@{
    ViewBag.Title = "createVisitType";
}
<!DOCTYPE html>
<html>
<head>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />;
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
</head>
<body>
   @using (Html.BeginForm())
   {
       @Html.ValidationSummary(true)
    <div id="visitBackground">
        <fieldset style="margin-top:-450px;">
            @Html.LabelFor(model => model.Title)
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
            <br />
            <br />
            @Html.LabelFor(model => model.Description)
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
            <br />
            <br />
            @Html.LabelFor(model => model.Active)
            @Html.EditorFor(model => model.Active)
            @Html.ValidationMessageFor(model => model.Active)
            <br />
            <br />
            <input type="submit" value="Create" />
        </fieldset>
        <br />
        <br />
        @Html.ActionLink("Visit Types", "visitType", null, new { @style = "padding:10px 10px 10px 10px;text-decoration:none;color:white;background-color:red;" })
    </div>
   }
</body>
</html>

mvctest/Views/SetUp/editCertification.cshtml
@{
    ViewBag.Title = "editCertification";
}
<!DOCTYPE html>
<html>
<head>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />;
</head>
<body>
    <div id="background">
        <fieldset style="margin-top:-450px;">
            Title
            <input type="text" align="left" />
            <br />
            <br />
            Description <input type="text" />
            <br />
            <br />
           

            Active
            <input type="checkbox" />
            <br />
            <br />
            <input type="submit" value="Create" />
        </fieldset>
        <br />
        <br />
        <button>Certifications</button>
    </div>
</body>
</html>

mvctest/Views/SetUp/editSwimTime.cshtml
@model TheSwimTimeSite.Models.ViewModels.CreateEditSwimTimeRulesViewModel


@{
    ViewBag.Title = "editSwimTime";
}

<!DOCTYPE html>
<html>
<head>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />;
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Scripts/JQuery1.6.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.16.custom.min.js")" type="text/javascript"></script>

    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            ('.datepicker').datepicker();
        })

    </script>

</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        <div id="visitBackground">
            <br />
            <fieldset style="margin-top:-500px;" align="left">
                <legend>Change SwimTime Settings</legend>
                @Html.HiddenFor(model => model.Creating.SwimTimeID)

                <table>
                    <tr>
                        <td>
                            Min-Hours
                            @Html.EditorFor(model => model.Creating.MinHoursPerVisit)
                            @Html.ValidationMessageFor(model => model.Creating.MinHoursPerVisit)

                        </td>
                    </tr>
                    <tr>
                        <td>
                            Max-Hours
                            @Html.EditorFor(model => model.Creating.MaxHoursPerVisit)
                            @Html.ValidationMessageFor(model => model.Creating.MaxHoursPerVisit)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Start Date
                            @Html.TextBoxFor(model => model.Creating.Start,
                                  new { @class = "datepicker" })
                            @Html.ValidationMessageFor(model => model.Creating.Start)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            End Date
                            @Html.TextBoxFor(model => model.Creating.End,
                                  new { @class = "datepicker" })
                            @Html.ValidationMessageFor(model => model.Creating.End)
                        </td>
                    </tr>

                    <tr>
                        <td>
                            @Html.LabelFor(model => model.Creating.Course)
                            @Html.DropDownListFor(m => m.Creating.Course.CRN, Model.Course, "--")
                            @Html.ValidationMessageFor(model => model.Creating.Course)
                        </td>
                    </tr>
                    
                    <tr>
                        <td>
                            <br />
                            <input type="submit" value="Save" style="border:none;color:white;background-color:red;padding:4px 20px 4px 20px;" />
                        </td>
                    </tr>
                </table>
            </fieldset>

            <br />
            @Html.ActionLink("SwimTime", "SwimTime", null, new { @style = "padding:10px 10px 10px 10px;text-decoration:none;color:white;background-color:red;" })
        </div>


    }
</body>
</html>

mvctest/Views/SetUp/editTerm.cshtml
@model TheSwimTimeSite.Models.ViewModels.CreateEditTermViewModel


@{
    ViewBag.Title = "editTerm";
}
<!DOCTYPE html>
<html>
<head>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />;
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Scripts/JQuery1.6.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.16.custom.min.js")" type="text/javascript"></script>

    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            ('.datepicker').datepicker();
        })
    
    </script>
</head>
<body>
    @Html.BeginForm(){ 
    @Html.ValidationSummary(true)
    <div id="visitBackground">
        <fieldset style="margin-top:-420px;">
            @Html.HiddenFor(model => model.Creating.TermID)
            <table>
                <tr>
                    <td align="left">
                        @Html.LabelFor(model => model.Creating.Quarter)
                        @Html.DropDownListFor(m => m.Creating.Quarter, Model.QuartersList, "--")
                        @Html.ValidationMessageFor(model => model.Creating.Quarter)
                    </td>

                </tr>
                <tr>
                    <td align="left">
                        @Html.LabelFor(model => model.Creating.Year)
                        @Html.EditorFor(model => model.Creating.Year)
                        @Html.ValidationMessageFor(model => model.Creating.Year)
                    </td>
                </tr>
                <tr>
                    <td align="left">
                        @Html.LabelFor(model => model.Creating.Start)
                        @Html.TextBoxFor(model => model.Creating.Start,
                    new { @class = "datepicker" })
                        @Html.ValidationMessageFor(model => model.Creating.Start)
                    </td>
                </tr>
                <tr>
                    <td align="left">
                        @Html.LabelFor(model => model.Creating.Endd)
                        @Html.TextBoxFor(model => model.Creating.Endd,
                    new { @class = "datepicker" })
                        @Html.ValidationMessageFor(model => model.Creating.Endd)
                    </td>
                </tr>
                <tr>
                    <td><input type="submit" value="Create" /></td>
                </tr>
            </table>
        </fieldset>
        <br />
        @Html.ActionLink("Terms", "Terms", null, new { @class = "button" })
    </div>
    
    
    
    
    }
</body>
</html>